routes/admin.php
<?php

Route::prefix('admin')->name('admin.')->group(function () {

    Route::get('login', 'Admin\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Admin\LoginController@login')->name('login.post');

    Route::group(['middleware' => ['checkUser:admin', 'auth:admin']], function () {

        Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

        resourceWithUpload('agent', 'Admin\AgentsController');

        Route::prefix('agent')->name('agent.')->group(function () {

            Route::resource('/{agent}/packages', 'Admin\PackageController')->names([
                'index' => 'packages.index',
                'create' => 'packages.create',
                'store' => 'packages.store',
                'edit' => 'packages.edit',
                'update' => 'packages.update',
                'destroy' => 'packages.delete',
            ]);

        });

        Route::get('packages','Admin\PackageController@list')->name('packages.all');
        Route::get('packages/create','Admin\PackageController@agents')->name('packages.agents');

        Route::resource('admin', 'Admin\AdminController')->names([
            'index' => 'admin.index',
            'create' => 'admin.create',
            'store' => 'admin.store',
            'edit' => 'admin.edit',
            'update' => 'admin.update',
            'destroy' => 'admin.delete',
        ]);
        Route::resource('settings', 'Admin\SettingsController')->names([
            'index' => 'settings.index',
            'create' => 'settings.create',
            'store' => 'settings.store',
            'edit' => 'settings.edit',
            'update' => 'settings.update',
            'destroy' => 'settings.delete',
        ]);

      Route::resource('amenities', 'Admin\AmenityController')->names([
            'index' => 'amenities.index',
            'create' => 'amenities.create',
            'store' => 'amenities.store',
            'edit' => 'amenities.edit',
            'update' => 'amenities.update',
            'destroy' => 'amenities.delete',
        ]);

        resourceWithUpload('hotels', 'Admin\HotelController');
        resourceWithUpload('airlines', 'Admin\AirlineController');

//        Route::post('hotels/process', 'Admin\HotelController@processImage');
//        Route::delete('hotels/revert', 'Admin\HotelController@revertImage');
//        Route::post('hotels/{id}/process', 'Admin\HotelController@processImage');
//        Route::delete('hotels/{id}/revert', 'Admin\HotelController@revertImage');
//        Route::get('hotels/{id}/load/{path}', 'Admin\HotelController@loadImage');
//        Route::resource('hotels', 'Admin\HotelController')->names([
//            'index' => 'hotels.index',
//            'create' => 'hotels.create',
//            'store' => 'hotels.store',
//            'edit' => 'hotels.edit',
//            'update' => 'hotels.update',
//            'destroy' => 'hotels.delete',
//        ]);

        Route::get('image-upload', 'Admin\SettingsController@imageUpload')->name('image.upload');
        Route::post('image-upload1', 'Admin\SettingsController@imageUploadPost')->name('image.upload.post');

        Route::resource('cities', 'Admin\CityController')->names([
            'index' => 'cities.index',
            'create' => 'cities.create',
            'store' => 'cities.store',
            'edit' => 'cities.edit',
            'update' => 'cities.update',
            'destroy' => 'cities.delete',
        ]);

        Route::resource('countries', 'Admin\CountryController')->names([
            'index' => 'countries.index',
            'create' => 'countries.create',
            'store' => 'countries.store',
            'edit' => 'countries.edit',
            'update' => 'countries.update',
            'destroy' => 'countries.delete',
        ]);

        Route::post('review/{review}/active', 'Admin\ReviewsController@active')->name('review.active');
        Route::resource('review', 'Admin\ReviewsController')->names([
            'index' => 'review.index',
            'create' => 'review.create',
            'store' => 'review.store',
            'edit' => 'review.edit',
            'update' => 'review.update',
            'destroy' => 'review.delete',
        ]);

        resource('booking','Admin\BookingController');
        Route::post('booking/{booking}', 'Admin\BookingController@update_status')->name('booking.update_status');

        Route::get('logout', 'Admin\LoginController@logout')->name('logout');



        Route::get('recipients', 'Admin\RecipientEmailsController@index')->name('recipient.index');



    });
});

routes/web.php
<?php

require "admin.php";
require "agent.php";

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Main\MainController@index')->name('main');

Route::post('/recipient-email', 'Main\RecipientEmailController@store')->name('main.recipient_email');

Route::get('register1', 'Agent\RegisterController@showForm1')->name('agent.register1');
Route::post('register1', 'Agent\RegisterController@postForm1')->name('post.register1');
Route::get('register2', 'Agent\RegisterController@showForm2')->name('agent.register2');
Route::post('register2', 'Agent\RegisterController@postForm2')->name('post.register2');
Route::get('login', 'Agent\LoginController@showLoginForm')->name('agent.login');
Route::post('login', 'Agent\LoginController@login');

Route::get('/package/{package}', 'Main\PackageController@view')->name('package.info');
Route::post('/package/{package}/review', 'Main\ReviewsController@save')->name('package.review');
Route::get('/review/{token}', 'Main\ReviewsController@verify')->name('review.verify');
Route::get('/booking/success', 'Main\BookingController@success')->name('booking.success');
Route::get('/booking/custom', 'Main\BookingController@bookCustomView')->name('booking.custom');
Route::post('/booking/custom', 'Main\BookingController@bookCustom')->name('booking.custom');
Route::get('/booking/{package}', 'Main\BookingController@bookPackageView')->name('booking.package');
Route::post('/booking/{package}', 'Main\BookingController@bookPackage')->name('booking.package');

Route::get('search', 'Main\SearchController@index')->name('search.index');
Route::get('search/ajax', 'Main\SearchController@ajax')->name('search.ajax');
Route::get('test', function () {
    \Debugbar::disable();
    return view('test');
});

Route::post('test', function (\Illuminate\Http\Request $request) {
    echo "<pre>";
    print_r($_POST);
    print_r($_FILES);
    echo "<pre>";
    die;
});

Route::post('file', function () {
    echo "<pre>";
    print_r($_FILES);
    echo "<pre>";
    die;
});

resources/views/admin/app.blade.php
@extends('templates.admin.app')


@section('body')
    @stack('img_css')
    @include('admin::sidebar')
    <div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">

        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            @include('partials.AlertComponent')

            @yield('content')

        </div>
    </section>
</div>

@stack('img_script')
@endsection()

resources/views/admin/sidebar.blade.php
@php
    $review = App\Models\Review::where('status_read', 0)->count();
    $booking_read = \App\Models\BookingRead::where('status_admin', 0)->count();
@endphp
<!-- Main Sidebar Container -->
@php

$review = App\Models\Review::where('status_read', 0)->count();

@endphp


<aside class="main-sidebar sidebar-dark-primary elevation-4">


	<!-- Sidebar -->
	<div class="sidebar">
		<!-- Sidebar user panel (optional) -->
		<div class="user-panel mt-3 pb-3 mb-3 d-flex">
			<div class="info">
				<a href="#" class="d-block">Alexander Pierce</a>
				<a class="nav-link text-light btn btn-danger" href="{{ route('admin.logout') }}"><i
							class="fa fa-sign-out fa-lg"></i> Logout</a>
			</div>
		</div>

		<!-- Sidebar Menu -->
		<nav class="mt-2">
			<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
				<!-- Add icons to the links using the .nav-icon class
					 with font-awesome or any other icon font library -->
				<li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.dashboard') }}" class="nav-link {{ isActiveRoute('admin.dashboard', true) }}">
						<i class="nav-icon fas fa-tachometer-alt"></i>
						<p>
							Dashboard
						</p>
					</a>
				</li>
				<li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.agent.index') }}" class="nav-link {{ isActiveRoute('admin.agent') }}">
						<i class="nav-icon fas  fa-user-tie"></i>
						<p>
							Agents
						</p>
					</a>
				</li>
				<li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.packages.all') }}" class="nav-link {{ isActiveRoute('packages.all', true) }}">
						<i class="nav-icon fas  fas fa-columns"></i>
						<p>
							All packages
						</p>
					</a>
				</li>
				<li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.admin.index') }}" class="nav-link {{isActiveRoute('admin.admin')}}">
						<i class="nav-icon fas fa-users"></i>
						<p>
							Admins
						</p>
					</a>
				</li>
				<li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.hotels.index') }}" class="nav-link {{isActiveRoute('admin.hotels')}}">
						<i class="nav-icon fas  fa-hospital"></i>
						<p>
							Hotels
						</p>
					</a>
				</li>
                <li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.amenities.index') }}" class="nav-link {{isActiveRoute('admin.amenities')}}">
						<i class="nav-icon fas  fa-box-open"></i>
						<p>
                            Amenities
						</p>
					</a>
				</li>
				<li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.cities.index') }}" class="nav-link {{isActiveRoute('admin.cities')}}">
						<i class="nav-icon fas   fa-bullseye"></i>
						<p>
							Cities
						</p>
					</a>
				</li>
				<li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.countries.index') }}" class="nav-link {{isActiveRoute('admin.countries')}}">
						<i class="nav-icon fas   fa-bullseye"></i>
						<p>
							Countries
						</p>
					</a>
				</li>
				<li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.airlines.index') }}" class="nav-link {{isActiveRoute('admin.airlines')}}">
						<i class="nav-icon fas  fa-plane"></i>
						<p>
							Airlines
						</p>
					</a>
				</li>
				<li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.review.index') }}" class="nav-link {{isActiveRoute('admin.review')}}">
						<i class="nav-icon fas  fa-comments"></i>
						<p>
							Reviews ({{$review}})
						</p>
					</a>
				</li>

				<li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.booking.index') }}" class="nav-link {{isActiveRoute('admin.booking')}}">
						<i class="nav-icon fas  fa-calendar-check"></i>
						<p>
							Bookings ({{$booking_read}})
						</p>
					</a>
				</li>
                <li class="nav-item has-treeview menu-open">
					<a href="{{ route('admin.recipient.index') }}" class="nav-link {{isActiveRoute('admin.recipient')}}">
						<i class="nav-icon fas  fa-calendar-check"></i>
						<p>
							Recipient emails
						</p>
					</a>
				</li>

                <li class="nav-item  has-treeview menu-open">
					<a href="{{ route('admin.settings.index') }}" class="nav-link {{isActiveRoute('admin.settings')}}">
						<i class="nav-icon fas  fa-edit"></i>
						<p>
							Settings
						</p>
					</a>
				</li>
			</ul>
		</nav>
		<!-- /.sidebar-menu -->
	</div>
	<!-- /.sidebar -->
</aside>